apiVersion: v1
kind: Pod 
metadata:
  name: test-vol
spec:
  containers:
  - image: coolgourav147/nginx-custom
    name: test-container 
    volumeMounts:
      - mountPath: /datal 
        name: first-volume
  volumes:
  - name: first-volume
    awsElasticBlockStore: 
      volumeID: ""
      fsType: ext4