apiVersion: v1
kind: Pod 
metadata:
  name: firstpod
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer
      imagePullPolicy: Never 
      volumeMounts:
        - name: test
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: test 
      configMap:
        name: envcm
        iteams: 
          - key: variable1
            path: newverable1
          - key: verable3
            path: newverable3