apiVersion: v1
kind: Pod 
metadata:
  name: firstpod
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer
      imagePullPolicy: Never
      env:
        - name: variablefromcm 
          valueFrom:
            configMapKeyRef:
            key: variable2
            name: envcm
        - name : variable fromcm2
          valueFrom:
            configMapKeyRef :
              key: env. sh
              name: formfilecm