apiVersion:  v1
kind: pod 

metadata: 
   name: myfirstpod
   namespace: test
   labels:
     app: myapp
     type: frountend
     
spec:
  containers:
    -name: containername
     image: coolgourav147//nginx-custom
     imagespullpolicy: Never
     resources:
        requests:
          memory: 200m
          cpu: 500m
        limits: 
          memory: 300m
          cpu: 0.5