apiVersion: v1
kind: Pod 
metadata:
  name: firstpod
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer
      imagePullPolicy: Never 
      volumeMounts:
        - mountPath: /secrets
          name: testsec
  volumes:
    - name: testsec 
      secret:
        secretName: secretname