apiVersion: v1
kind: Pod 
metadata:
  name: firstpod
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer
      imagePullPolicy: Never
      env:
        - name: myvariable 
          valueFrom:
          secretKeyRef:
            key: variable1
            name: secretsname

      envFrom: 
        - secretRef: 
            name: secretsname