apiVersion: v1 
kind: Pod
metadata:
  name: pod13
spec:
  containers:
    - image: coolgourav147/nginx-custom 
      name: firstcontainer 
      imagePullPolicy: Never
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference: 
            matchExpressions:
              - key: size 
                operator: In 
                values:
                  - small
          weight: 1