apiVersion: v1
kind: Pod 
metadata:
  name: pod10 
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer
      imagePullPolicy: Never
  nodeSelector:
    size: "large"