apiVersion: v1
kind: Pod 
metadata:
  name: pod4
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: firstcontainer 
      imagePullPolicy: Never
  tolerations:
    - effect: "NoSchedule"
      key: "mysize"
      operator: "Equal" 
      value: "large"
      tolerationseconds: 60

# kubectl taint node worker01 mysize=large:NoSchedule